### PR TITLE
Added missing font-awesome icon names

### PR DESCRIPTION
**Pull request by Jayadev6191**
- Added missing icon names
- Corrected the fontawesome-5.json structure to a valid json (Tested Here) after reading through the formatting rules(https://www.w3schools.com/js/js_json_syntax.asp)

### CODE REVIEW

**Comment by vrundakansara** [comment]
@Jayadev6191 - You have added the same value thrice. Can you please check again?

**Comment by Jayadev6191** [comment]
@vrundakansara My bad. I have written a script to do this and I found a bug during concatenating the missing icons to the existing icons. Will update this PR. Thanks for pointing out! :)

**Comment by Jayadev6191** [comment]
@vrundakansara Can you review it now. Also do you think it makes sense to have a build script to build new icons automatically when the official repo (website) adds new icons. Let me know so that I can raise another PR with the below script.

```
const fs = require('fs');
let icons = require('./curr_icons.js'); // Existing icon names in the json

/* 
    Links for the icons name from official reposiroty 
    Note that this script is only reading the file names not the actual files
    https://github.com/FortAwesome/Font-Awesome/tree/master/advanced-options/
*/
const brandsFolder = './advanced-options/raw-svg/brands';
const regularFolder = './advanced-options/raw-svg/regular';
const solidFolder = './advanced-options/raw-svg/solid'; 

let missing_brands = [];
let missing_regular = [];
let missing_solid = [];

function buldIconList() {
    let brand = new Promise(function(resolve, reject){
        fs.readdir(brandsFolder, (err, files) => {
            if(!err) {
                files.forEach(file => {  
                    const brand_icon = `fab fa-${file.split('.')[0]}`;
                    if(!icons.includes(brand_icon)) {
                        missing_brands.push(brand_icon);
                    };
                });
                // console.log("missing brands" + missing_brands);
                resolve(missing_brands);
            } else {
                reject(err);
            }
        })
    });
    
    let regular = new Promise(function(resolve, reject){
        fs.readdir(regularFolder, (err, files) => {
            if(!err) {
                files.forEach(file => {  
                    const regular_icon = `far fa-${file.split('.')[0]}`;
                    if(!icons.includes(regular_icon)) {
                        missing_regular.push(regular_icon);
                        // icons.push(regular_icon);
                    };
                });
                resolve(missing_regular);
            } else {
                reject(err);
            }
        })
    });

    let solid = new Promise(function(resolve, reject){
        fs.readdir(solidFolder, (err, files) => {
            if(!err) {
                files.forEach(file => {  
                    const solid_icon = `fas fa-${file.split('.')[0]}`;
                    if(!icons.includes(solid_icon)) {
                        missing_solid.push(solid_icon);
                        // icons.push(solid_icon);
                    };
                });
                resolve(missing_solid);
            } else {
                reject(err);
            }
        })
    });


    return Promise.all([brand, regular, solid]).then(function(res){
        console.log(`brand length ${res[0].length}, regular length: ${res[1].length}, solid length: ${res[2].length} `)
        var consolidated = [].concat(icons, ...res);
        console.log(consolidated.length);
        return consolidated;
    }).catch(function(err){
        throw err;
    });
}

const build = buldIconList().then((data)=> {
    fs.writeFile("./output.json" , JSON.stringify(data), 'utf8', function (err) {
        if (err) {
            return console.log(err);
        }
        
        console.log("The file was saved!");
    }); 
});

```

**Comment by vrundakansara** [comment]
@Jayadev6191 - Thank you. Yes, indeed that would be helpful.

**Pull request merged**
